-- MySQL Script generated by MySQL Workbench
-- Fri Jul 31 12:27:14 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema banquito_solidario
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `banquito_solidario` ;

-- -----------------------------------------------------
-- Schema banquito_solidario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banquito_solidario` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `banquito_solidario` ;

-- -----------------------------------------------------
-- Table `banquito_solidario`.`fondorotatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banquito_solidario`.`fondorotatorio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `organizacion` VARCHAR(200) NOT NULL DEFAULT '',
  `capitalInicial` DECIMAL(12,2) NOT NULL,
  `capitalDisponible` DECIMAL(12,2) NOT NULL,
  `moneda` CHAR(3) NOT NULL DEFAULT 'PEN',
  `estado` VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
  `descripcion` TEXT NULL DEFAULT NULL,
  `reglamento` TEXT NULL DEFAULT NULL,
  `condiciones` TEXT NULL DEFAULT NULL,
  `fechaCierre` DATETIME(3) NULL DEFAULT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `banquito_solidario`.`socio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banquito_solidario`.`socio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(20) NOT NULL,
  `dni` CHAR(8) NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidoPaterno` VARCHAR(50) NOT NULL,
  `apellidoMaterno` VARCHAR(50) NOT NULL,
  `genero` CHAR(1) NOT NULL,
  `fechaNacimiento` DATETIME(3) NULL DEFAULT NULL,
  `estadoCivil` CHAR(1) NULL DEFAULT NULL,
  `telefono` VARCHAR(9) NULL DEFAULT NULL,
  `direccion` VARCHAR(200) NULL DEFAULT NULL,
  `email` VARCHAR(150) NULL DEFAULT NULL,
  `fechaIngreso` DATETIME(3) NOT NULL,
  `estado` CHAR(1) NOT NULL DEFAULT 'A',
  `fotoUrl` VARCHAR(191) NULL DEFAULT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `Socio_codigo_key` ON `banquito_solidario`.`socio` (`codigo` ASC) VISIBLE;

CREATE UNIQUE INDEX `Socio_dni_key` ON `banquito_solidario`.`socio` (`dni` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `banquito_solidario`.`FondoSocio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banquito_solidario`.`FondoSocio` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `fondorotatorio_id` INT NOT NULL,
  `socio_id` INT NOT NULL,
  `fechaIngreso` DATETIME(3) NULL,
  `fechaSalida` DATETIME(3) NULL,
  `numeroSocio` INT NULL,
  `cargo` VARCHAR(45) NULL,
  `nivel` VARCHAR(45) NULL,
  `observacion` VARCHAR(45) NULL,
  `fechaAprobacion` DATETIME(3) NULL,
  `usuario_id` INT NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `fk_fondorotatorio_has_socio_fondorotatorio1`
    FOREIGN KEY (`fondorotatorio_id`)
    REFERENCES `banquito_solidario`.`fondorotatorio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fondorotatorio_has_socio_socio1`
    FOREIGN KEY (`socio_id`)
    REFERENCES `banquito_solidario`.`socio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_fondorotatorio_has_socio_socio1_idx` ON `banquito_solidario`.`FondoSocio` (`socio_id` ASC) VISIBLE;

CREATE INDEX `fk_fondorotatorio_has_socio_fondorotatorio1_idx` ON `banquito_solidario`.`FondoSocio` (`fondorotatorio_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `banquito_solidario`.`cuentaahorro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banquito_solidario`.`cuentaahorro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `saldo` DECIMAL(12,2) NOT NULL,
  `estado` VARCHAR(20) NOT NULL DEFAULT 'ACTIVA',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `FondoSocio_Id` INT NOT NULL,
  PRIMARY KEY (`id`, `FondoSocio_Id`),
  CONSTRAINT `fk_cuentaahorro_FondoSocio1`
    FOREIGN KEY (`FondoSocio_Id`)
    REFERENCES `banquito_solidario`.`FondoSocio` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_cuentaahorro_FondoSocio1_idx` ON `banquito_solidario`.`cuentaahorro` (`FondoSocio_Id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `banquito_solidario`.`ahorromovimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banquito_solidario`.`ahorromovimiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(20) NOT NULL,
  `monto` DECIMAL(12,2) NOT NULL,
  `saldoAntes` DECIMAL(12,2) NOT NULL,
  `saldoDespues` DECIMAL(12,2) NOT NULL,
  `metodoPago` VARCHAR(20) NOT NULL DEFAULT 'EFECTIVO',
  `comprobante` VARCHAR(100) NULL DEFAULT NULL,
  `observacion` TEXT NULL DEFAULT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `cuentaahorro_id` INT NOT NULL,
  PRIMARY KEY (`id`, `cuentaahorro_id`),
  CONSTRAINT `fk_ahorromovimiento_cuentaahorro1`
    FOREIGN KEY (`cuentaahorro_id`)
    REFERENCES `banquito_solidario`.`cuentaahorro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_ahorromovimiento_cuentaahorro1_idx` ON `banquito_solidario`.`ahorromovimiento` (`cuentaahorro_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `banquito_solidario`.`aporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banquito_solidario`.`aporte` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(20) NOT NULL,
  `monto` DECIMAL(12,2) NOT NULL,
  `periodo` CHAR(7) NOT NULL,
  `fechaAporte` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `metodoPago` VARCHAR(20) NOT NULL DEFAULT 'EFECTIVO',
  `comprobante` VARCHAR(100) NULL DEFAULT NULL,
  `observacion` TEXT NULL DEFAULT NULL,
  `estado` VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `FondoSocio_Id` INT NOT NULL,
  PRIMARY KEY (`id`, `FondoSocio_Id`),
  CONSTRAINT `fk_aporte_FondoSocio1`
    FOREIGN KEY (`FondoSocio_Id`)
    REFERENCES `banquito_solidario`.`FondoSocio` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_aporte_FondoSocio1_idx` ON `banquito_solidario`.`aporte` (`FondoSocio_Id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `banquito_solidario`.`caja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banquito_solidario`.`caja` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `tipo` VARCHAR(20) NOT NULL DEFAULT 'PRINCIPAL',
  `moneda` CHAR(3) NOT NULL DEFAULT 'PEN',
  `saldoInicial` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `saldoActual` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `estado` VARCHAR(20) NOT NULL DEFAULT 'ACTIVA',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `fondorotatorio_id` INT NOT NULL,
  PRIMARY KEY (`id`, `fondorotatorio_id`),
  CONSTRAINT `fk_caja_fondorotatorio`
    FOREIGN KEY (`fondorotatorio_id`)
    REFERENCES `banquito_solidario`.`fondorotatorio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `Caja_codigo_key` ON `banquito_solidario`.`caja` (`codigo` ASC) VISIBLE;

CREATE INDEX `fk_caja_fondorotatorio_idx` ON `banquito_solidario`.`caja` (`fondorotatorio_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `banquito_solidario`.`arqueocaja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banquito_solidario`.`arqueocaja` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(30) NOT NULL,
  `fechaArqueo` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `saldoSistema` DECIMAL(12,2) NOT NULL,
  `saldoFisico` DECIMAL(12,2) NOT NULL,
  `diferencia` DECIMAL(12,2) NOT NULL,
  `observacion` TEXT NULL DEFAULT NULL,
  `estado` VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `fechaAprobacion` DATETIME(3) NULL DEFAULT NULL,
  `caja_id` INT NOT NULL,
  PRIMARY KEY (`id`, `caja_id`),
  CONSTRAINT `fk_arqueocaja_caja1`
    FOREIGN KEY (`caja_id`)
    REFERENCES `banquito_solidario`.`caja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `ArqueoCaja_codigo_key` ON `banquito_solidario`.`arqueocaja` (`codigo` ASC) VISIBLE;

CREATE INDEX `fk_arqueocaja_caja1_idx` ON `banquito_solidario`.`arqueocaja` (`caja_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `banquito_solidario`.`auditlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banquito_solidario`.`auditlog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tabla` VARCHAR(50) NOT NULL,
  `registroId` INT NOT NULL,
  `operacion` VARCHAR(20) NOT NULL,
  `datosAnteriores` JSON NULL DEFAULT NULL,
  `datosNuevos` JSON NULL DEFAULT NULL,
  `ip` VARCHAR(45) NULL DEFAULT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `AuditLog_tabla_registroId_idx` ON `banquito_solidario`.`auditlog` (`tabla` ASC, `registroId` ASC) VISIBLE;

CREATE INDEX `AuditLog_createdAt_idx` ON `banquito_solidario`.`auditlog` (`createdAt` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `banquito_solidario`.`beneficiario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banquito_solidario`.`beneficiario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dni` CHAR(8) NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidoPaterno` VARCHAR(50) NOT NULL,
  `apellidoMaterno` VARCHAR(50) NOT NULL,
  `fechaNacimiento` DATETIME(3) NULL DEFAULT NULL,
  `parentesco` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(9) NULL DEFAULT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `socio_id` INT NOT NULL,
  PRIMARY KEY (`id`, `socio_id`),
  CONSTRAINT `fk_beneficiario_socio1`
    FOREIGN KEY (`socio_id`)
    REFERENCES `banquito_solidario`.`socio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_beneficiario_socio1_idx` ON `banquito_solidario`.`beneficiario` (`socio_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `banquito_solidario`.`conceptocaja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banquito_solidario`.`conceptocaja` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  `afectaSaldo` VARCHAR(10) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `requiereComprobante` TINYINT(1) NOT NULL DEFAULT '1',
  `orden` INT NOT NULL DEFAULT '0',
  `estado` VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `ConceptoCaja_codigo_key` ON `banquito_solidario`.`conceptocaja` (`codigo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `banquito_solidario`.`prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banquito_solidario`.`prestamo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `monto` DECIMAL(12,2) NOT NULL,
  `tasaInteres` DECIMAL(5,2) NOT NULL,
  `numeroCuotas` INT NOT NULL,
  `montoCuota` DECIMAL(12,2) NOT NULL,
  `totalInteres` DECIMAL(12,2) NOT NULL,
  `fechaDesembolso` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `fechaPrimerVencimiento` DATETIME(3) NOT NULL,
  `estado` VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `FondoSocio_Id` INT NOT NULL,
  PRIMARY KEY (`id`, `FondoSocio_Id`),
  CONSTRAINT `fk_prestamo_FondoSocio1`
    FOREIGN KEY (`FondoSocio_Id`)
    REFERENCES `banquito_solidario`.`FondoSocio` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_prestamo_FondoSocio1_idx` ON `banquito_solidario`.`prestamo` (`FondoSocio_Id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `banquito_solidario`.`cuotaprestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banquito_solidario`.`cuotaprestamo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `fechaVencimiento` DATETIME(3) NOT NULL,
  `monto` DECIMAL(12,2) NOT NULL,
  `interes` DECIMAL(12,2) NOT NULL,
  `amortizacion` DECIMAL(12,2) NOT NULL,
  `saldo` DECIMAL(12,2) NOT NULL,
  `montoPagado` DECIMAL(12,2) NOT NULL,
  `saldoPendiente` DECIMAL(12,2) NOT NULL,
  `fechaPago` DATETIME(3) NULL DEFAULT NULL,
  `estado` VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
  `metodoPago` VARCHAR(20) NULL DEFAULT NULL,
  `comprobante` VARCHAR(100) NULL DEFAULT NULL,
  `prestamo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `prestamo_id`),
  CONSTRAINT `fk_cuotaprestamo_prestamo1`
    FOREIGN KEY (`prestamo_id`)
    REFERENCES `banquito_solidario`.`prestamo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_cuotaprestamo_prestamo1_idx` ON `banquito_solidario`.`cuotaprestamo` (`prestamo_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `banquito_solidario`.`documentosocio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banquito_solidario`.`documentosocio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipoDocumento` VARCHAR(50) NOT NULL,
  `nombreArchivo` VARCHAR(255) NOT NULL,
  `rutaArchivo` VARCHAR(500) NOT NULL,
  `mimeType` VARCHAR(100) NOT NULL,
  `tamaño` INT NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `socio_id` INT NOT NULL,
  PRIMARY KEY (`id`, `socio_id`),
  CONSTRAINT `fk_documentosocio_socio1`
    FOREIGN KEY (`socio_id`)
    REFERENCES `banquito_solidario`.`socio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_documentosocio_socio1_idx` ON `banquito_solidario`.`documentosocio` (`socio_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `banquito_solidario`.`flujocajaproyectado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banquito_solidario`.`flujocajaproyectado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  `concepto` VARCHAR(100) NOT NULL,
  `montoProyectado` DECIMAL(12,2) NOT NULL,
  `montoReal` DECIMAL(12,2) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `estado` VARCHAR(20) NOT NULL DEFAULT 'PROYECTADO',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `caja_id` INT NOT NULL,
  PRIMARY KEY (`id`, `caja_id`),
  CONSTRAINT `fk_flujocajaproyectado_caja1`
    FOREIGN KEY (`caja_id`)
    REFERENCES `banquito_solidario`.`caja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_flujocajaproyectado_caja1_idx` ON `banquito_solidario`.`flujocajaproyectado` (`caja_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `banquito_solidario`.`movimientocaja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banquito_solidario`.`movimientocaja` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(30) NOT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  `monto` DECIMAL(12,2) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `comprobante` VARCHAR(100) NULL DEFAULT NULL,
  `metodoPago` VARCHAR(20) NOT NULL DEFAULT 'EFECTIVO',
  `referencia` VARCHAR(100) NULL DEFAULT NULL,
  `fechaMovimiento` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `estado` VARCHAR(20) NOT NULL DEFAULT 'REGISTRADO',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `caja_id` INT NOT NULL,
  `conceptocaja_id` INT NOT NULL,
  PRIMARY KEY (`id`, `caja_id`, `conceptocaja_id`),
  CONSTRAINT `fk_movimientocaja_caja1`
    FOREIGN KEY (`caja_id`)
    REFERENCES `banquito_solidario`.`caja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimientocaja_conceptocaja1`
    FOREIGN KEY (`conceptocaja_id`)
    REFERENCES `banquito_solidario`.`conceptocaja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `MovimientoCaja_codigo_key` ON `banquito_solidario`.`movimientocaja` (`codigo` ASC) VISIBLE;

CREATE INDEX `MovimientoCaja_fechaMovimiento_idx` ON `banquito_solidario`.`movimientocaja` (`fechaMovimiento` ASC) VISIBLE;

CREATE INDEX `MovimientoCaja_estado_idx` ON `banquito_solidario`.`movimientocaja` (`estado` ASC) VISIBLE;

CREATE INDEX `fk_movimientocaja_caja1_idx` ON `banquito_solidario`.`movimientocaja` (`caja_id` ASC) VISIBLE;

CREATE INDEX `fk_movimientocaja_conceptocaja1_idx` ON `banquito_solidario`.`movimientocaja` (`conceptocaja_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `banquito_solidario`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banquito_solidario`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidoPaterno` VARCHAR(50) NOT NULL,
  `apellidoMaterno` VARCHAR(50) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `correo` VARCHAR(150) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `rol` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL DEFAULT 'ACTIVO',
  `ultimoAcceso` DATETIME(3) NULL DEFAULT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `Usuario_username_key` ON `banquito_solidario`.`usuario` (`username` ASC) VISIBLE;

CREATE UNIQUE INDEX `Usuario_correo_key` ON `banquito_solidario`.`usuario` (`correo` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
